language: go
go:
- "1.7"
- "1.8"
- "1.9"
- "1.10"
- master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
branches:
  only:
  - master
install:
- go get github.com/spf13/pflag
- go get github.com/pkg/errors
- go get github.com/jung-kurt/gofpdf
